name: Scheduled Service Call - Ingest New Stories from HN

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST https://www.meatballs.live/api/services/ingest/new-stories?apiKey=$INGEST_API_KEY&dataSource=hn&max=25
